// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CXX__SCHEMES_SCHEMA_COMMON_SMEV_SMEV_SUPPLEMENTARY_COMMONS_1_0_1_PSKEL_HXX
#define CXX__SCHEMES_SCHEMA_COMMON_SMEV_SMEV_SUPPLEMENTARY_COMMONS_1_0_1_PSKEL_HXX

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

// Forward declarations
//
namespace SMEV
{
  class AttachmentRefType_pskel;
  class PrimaryIdentityDocumentType_pskel;
  class AnyIdentityDocumentType_pskel;
  class NotRestrictedDocumentType_pskel;
  class PassportRFType_pskel;
  class SovietPassportType_pskel;
  class InternationalPassportRFType_pskel;
  class MilitaryPassportDocumentType_pskel;
  class DrivingLicenseRFType_pskel;
  class RFC2046MimeTypesType_pskel;
  class PostalCodeRFType_pskel;
  class PhoneNumberRFType_pskel;
  class EmailAddressType_pskel;
  class LegalPersonINNType_pskel;
  class PhysicalPersonINNType_pskel;
  class SNILSType_pskel;
  class KPPType_pskel;
  class OGRNCompanyType_pskel;
  class OGRNSoleProprietorType_pskel;
  class CadastralNumberType_pskel;
  class OKATOType_pskel;
  class GenderType_pskel;
  class SovietStyleDocumentSeriesType_pskel;
  class digits_7_pskel;
  class digits_6_pskel;
  class digits_4_pskel;
  class digits_2_pskel;
  class rus_and_num_pskel;
  class rus_and_num_500_pskel;
  class rus_and_num_200_pskel;
  class rus_and_num_100_pskel;
  class rus_and_num_50_pskel;
  class rus_pskel;
  class rus_500_pskel;
  class rus_200_pskel;
  class rus_100_pskel;
  class rus_50_pskel;
  class string_500_pskel;
  class string_200_pskel;
  class string_100_pskel;
  class string_50_pskel;
  class string_20_pskel;
  class string_10_pskel;
  class Number_pskel;
  class Series_pskel;
  class Series1_pskel;
}


#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_PARSER_USE_CHAR
#define XSD_CXX_PARSER_USE_CHAR
#endif

#include <xsd/cxx/xml/char-utf8.hxx>
#include <xsd/cxx/xml/error-handler.hxx>
#include <xsd/cxx/parser/exceptions.hxx>
#include <xsd/cxx/parser/elements.hxx>
#include <xsd/cxx/parser/xml-schema.hxx>
#include <xsd/cxx/parser/non-validating/parser.hxx>
#include <xsd/cxx/parser/non-validating/xml-schema-pskel.hxx>
#include <xsd/cxx/parser/non-validating/xml-schema-pimpl.hxx>
#include <xsd/cxx/parser/xerces/elements.hxx>

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  typedef ::xsd::cxx::parser::string_sequence< char > string_sequence;
  typedef ::xsd::cxx::parser::qname< char > qname;
  typedef ::xsd::cxx::parser::buffer buffer;
  typedef ::xsd::cxx::parser::time_zone time_zone;
  typedef ::xsd::cxx::parser::gday gday;
  typedef ::xsd::cxx::parser::gmonth gmonth;
  typedef ::xsd::cxx::parser::gyear gyear;
  typedef ::xsd::cxx::parser::gmonth_day gmonth_day;
  typedef ::xsd::cxx::parser::gyear_month gyear_month;
  typedef ::xsd::cxx::parser::date date;
  typedef ::xsd::cxx::parser::time time;
  typedef ::xsd::cxx::parser::date_time date_time;
  typedef ::xsd::cxx::parser::duration duration;

  // Base parser skeletons.
  //
  typedef ::xsd::cxx::parser::parser_base< char > parser_base;
  typedef ::xsd::cxx::parser::non_validating::empty_content< char > empty_content;
  typedef ::xsd::cxx::parser::non_validating::simple_content< char > simple_content;
  typedef ::xsd::cxx::parser::non_validating::complex_content< char > complex_content;
  typedef ::xsd::cxx::parser::non_validating::list_base< char > list_base;

  // Parser skeletons and implementations for the XML Schema
  // built-in types.
  //
  typedef ::xsd::cxx::parser::non_validating::any_type_pskel< char > any_type_pskel;
  typedef ::xsd::cxx::parser::non_validating::any_type_pimpl< char > any_type_pimpl;

  typedef ::xsd::cxx::parser::non_validating::any_simple_type_pskel< char > any_simple_type_pskel;
  typedef ::xsd::cxx::parser::non_validating::any_simple_type_pimpl< char > any_simple_type_pimpl;

  typedef ::xsd::cxx::parser::non_validating::byte_pskel< char > byte_pskel;
  typedef ::xsd::cxx::parser::non_validating::byte_pimpl< char > byte_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_byte_pskel< char > unsigned_byte_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_byte_pimpl< char > unsigned_byte_pimpl;

  typedef ::xsd::cxx::parser::non_validating::short_pskel< char > short_pskel;
  typedef ::xsd::cxx::parser::non_validating::short_pimpl< char > short_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_short_pskel< char > unsigned_short_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_short_pimpl< char > unsigned_short_pimpl;

  typedef ::xsd::cxx::parser::non_validating::int_pskel< char > int_pskel;
  typedef ::xsd::cxx::parser::non_validating::int_pimpl< char > int_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_int_pskel< char > unsigned_int_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_int_pimpl< char > unsigned_int_pimpl;

  typedef ::xsd::cxx::parser::non_validating::long_pskel< char > long_pskel;
  typedef ::xsd::cxx::parser::non_validating::long_pimpl< char > long_pimpl;

  typedef ::xsd::cxx::parser::non_validating::unsigned_long_pskel< char > unsigned_long_pskel;
  typedef ::xsd::cxx::parser::non_validating::unsigned_long_pimpl< char > unsigned_long_pimpl;

  typedef ::xsd::cxx::parser::non_validating::integer_pskel< char > integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::integer_pimpl< char > integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::non_positive_integer_pskel< char > non_positive_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::non_positive_integer_pimpl< char > non_positive_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::non_negative_integer_pskel< char > non_negative_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::non_negative_integer_pimpl< char > non_negative_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::positive_integer_pskel< char > positive_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::positive_integer_pimpl< char > positive_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::negative_integer_pskel< char > negative_integer_pskel;
  typedef ::xsd::cxx::parser::non_validating::negative_integer_pimpl< char > negative_integer_pimpl;

  typedef ::xsd::cxx::parser::non_validating::boolean_pskel< char > boolean_pskel;
  typedef ::xsd::cxx::parser::non_validating::boolean_pimpl< char > boolean_pimpl;

  typedef ::xsd::cxx::parser::non_validating::float_pskel< char > float_pskel;
  typedef ::xsd::cxx::parser::non_validating::float_pimpl< char > float_pimpl;

  typedef ::xsd::cxx::parser::non_validating::double_pskel< char > double_pskel;
  typedef ::xsd::cxx::parser::non_validating::double_pimpl< char > double_pimpl;

  typedef ::xsd::cxx::parser::non_validating::decimal_pskel< char > decimal_pskel;
  typedef ::xsd::cxx::parser::non_validating::decimal_pimpl< char > decimal_pimpl;

  typedef ::xsd::cxx::parser::non_validating::string_pskel< char > string_pskel;
  typedef ::xsd::cxx::parser::non_validating::string_pimpl< char > string_pimpl;

  typedef ::xsd::cxx::parser::non_validating::normalized_string_pskel< char > normalized_string_pskel;
  typedef ::xsd::cxx::parser::non_validating::normalized_string_pimpl< char > normalized_string_pimpl;

  typedef ::xsd::cxx::parser::non_validating::token_pskel< char > token_pskel;
  typedef ::xsd::cxx::parser::non_validating::token_pimpl< char > token_pimpl;

  typedef ::xsd::cxx::parser::non_validating::name_pskel< char > name_pskel;
  typedef ::xsd::cxx::parser::non_validating::name_pimpl< char > name_pimpl;

  typedef ::xsd::cxx::parser::non_validating::nmtoken_pskel< char > nmtoken_pskel;
  typedef ::xsd::cxx::parser::non_validating::nmtoken_pimpl< char > nmtoken_pimpl;

  typedef ::xsd::cxx::parser::non_validating::nmtokens_pskel< char > nmtokens_pskel;
  typedef ::xsd::cxx::parser::non_validating::nmtokens_pimpl< char > nmtokens_pimpl;

  typedef ::xsd::cxx::parser::non_validating::ncname_pskel< char > ncname_pskel;
  typedef ::xsd::cxx::parser::non_validating::ncname_pimpl< char > ncname_pimpl;

  typedef ::xsd::cxx::parser::non_validating::language_pskel< char > language_pskel;
  typedef ::xsd::cxx::parser::non_validating::language_pimpl< char > language_pimpl;

  typedef ::xsd::cxx::parser::non_validating::id_pskel< char > id_pskel;
  typedef ::xsd::cxx::parser::non_validating::id_pimpl< char > id_pimpl;

  typedef ::xsd::cxx::parser::non_validating::idref_pskel< char > idref_pskel;
  typedef ::xsd::cxx::parser::non_validating::idref_pimpl< char > idref_pimpl;

  typedef ::xsd::cxx::parser::non_validating::idrefs_pskel< char > idrefs_pskel;
  typedef ::xsd::cxx::parser::non_validating::idrefs_pimpl< char > idrefs_pimpl;

  typedef ::xsd::cxx::parser::non_validating::uri_pskel< char > uri_pskel;
  typedef ::xsd::cxx::parser::non_validating::uri_pimpl< char > uri_pimpl;

  typedef ::xsd::cxx::parser::non_validating::qname_pskel< char > qname_pskel;
  typedef ::xsd::cxx::parser::non_validating::qname_pimpl< char > qname_pimpl;

  typedef ::xsd::cxx::parser::non_validating::base64_binary_pskel< char > base64_binary_pskel;
  typedef ::xsd::cxx::parser::non_validating::base64_binary_pimpl< char > base64_binary_pimpl;

  typedef ::xsd::cxx::parser::non_validating::hex_binary_pskel< char > hex_binary_pskel;
  typedef ::xsd::cxx::parser::non_validating::hex_binary_pimpl< char > hex_binary_pimpl;

  typedef ::xsd::cxx::parser::non_validating::date_pskel< char > date_pskel;
  typedef ::xsd::cxx::parser::non_validating::date_pimpl< char > date_pimpl;

  typedef ::xsd::cxx::parser::non_validating::date_time_pskel< char > date_time_pskel;
  typedef ::xsd::cxx::parser::non_validating::date_time_pimpl< char > date_time_pimpl;

  typedef ::xsd::cxx::parser::non_validating::duration_pskel< char > duration_pskel;
  typedef ::xsd::cxx::parser::non_validating::duration_pimpl< char > duration_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gday_pskel< char > gday_pskel;
  typedef ::xsd::cxx::parser::non_validating::gday_pimpl< char > gday_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gmonth_pskel< char > gmonth_pskel;
  typedef ::xsd::cxx::parser::non_validating::gmonth_pimpl< char > gmonth_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gmonth_day_pskel< char > gmonth_day_pskel;
  typedef ::xsd::cxx::parser::non_validating::gmonth_day_pimpl< char > gmonth_day_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gyear_pskel< char > gyear_pskel;
  typedef ::xsd::cxx::parser::non_validating::gyear_pimpl< char > gyear_pimpl;

  typedef ::xsd::cxx::parser::non_validating::gyear_month_pskel< char > gyear_month_pskel;
  typedef ::xsd::cxx::parser::non_validating::gyear_month_pimpl< char > gyear_month_pimpl;

  typedef ::xsd::cxx::parser::non_validating::time_pskel< char > time_pskel;
  typedef ::xsd::cxx::parser::non_validating::time_pimpl< char > time_pimpl;

  // Exceptions. See libxsd/xsd/cxx/parser/exceptions.hxx for details.
  //
  typedef ::xsd::cxx::parser::exception< char > exception;

  // Parsing diagnostics.
  //
  typedef ::xsd::cxx::parser::severity severity;
  typedef ::xsd::cxx::parser::error< char > error;
  typedef ::xsd::cxx::parser::diagnostics< char > diagnostics;
  typedef ::xsd::cxx::parser::parsing< char > parsing;

  // Error handler. See libxsd/xsd/cxx/xml/error-handler.hxx for details.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // Read-only string.
  //
  typedef ::xsd::cxx::ro_string< char > ro_string;

  // Parsing flags. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::flags flags;

  // Parsing properties. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::properties< char > properties;

  // Document type. See libxsd/xsd/cxx/parser/xerces/elements.hxx
  // for details.
  //
  typedef ::xsd::cxx::parser::xerces::document< char > document;
}

namespace SMEV
{
  class AttachmentRefType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    attachmentId (const ::std::string&);

    virtual void
    post_AttachmentRefType ();

    // Parser construction API.
    //
    void
    attachmentId_parser (::xml_schema::string_pskel&);

    void
    parsers (::xml_schema::string_pskel& /* attachmentId */);

    // Constructor.
    //
    AttachmentRefType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _attribute_impl (const ::xml_schema::ro_string&,
                     const ::xml_schema::ro_string&,
                     const ::xml_schema::ro_string&);

    protected:
    ::xml_schema::string_pskel* attachmentId_parser_;
  };

  class PrimaryIdentityDocumentType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    PassportRF ();

    virtual void
    ForeignPassport ();

    virtual void
    ResidencePermitRF ();

    virtual void
    post_PrimaryIdentityDocumentType ();

    // Parser construction API.
    //
    void
    PassportRF_parser (::SMEV::PassportRFType_pskel&);

    void
    ForeignPassport_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    ResidencePermitRF_parser (::SMEV::InternationalPassportRFType_pskel&);

    void
    parsers (::SMEV::PassportRFType_pskel& /* PassportRF */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* ForeignPassport */,
             ::SMEV::InternationalPassportRFType_pskel& /* ResidencePermitRF */);

    // Constructor.
    //
    PrimaryIdentityDocumentType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::PassportRFType_pskel* PassportRF_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* ForeignPassport_parser_;
    ::SMEV::InternationalPassportRFType_pskel* ResidencePermitRF_parser_;
  };

  class AnyIdentityDocumentType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    PassportRF ();

    virtual void
    ForeignPassport ();

    virtual void
    ResidencePermitRF ();

    virtual void
    InternationalPassportRF ();

    virtual void
    MilitaryPassport ();

    virtual void
    SailorPassport ();

    virtual void
    SovietPassport ();

    virtual void
    BirthCertificate ();

    virtual void
    DrivingLicenseRF ();

    virtual void
    ReleaseCertificate ();

    virtual void
    PassportLossCertificate ();

    virtual void
    Form9Certificate ();

    virtual void
    TemporaryIdentityCardRF ();

    virtual void
    post_AnyIdentityDocumentType ();

    // Parser construction API.
    //
    void
    PassportRF_parser (::SMEV::PassportRFType_pskel&);

    void
    ForeignPassport_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    ResidencePermitRF_parser (::SMEV::InternationalPassportRFType_pskel&);

    void
    InternationalPassportRF_parser (::SMEV::InternationalPassportRFType_pskel&);

    void
    MilitaryPassport_parser (::SMEV::MilitaryPassportDocumentType_pskel&);

    void
    SailorPassport_parser (::SMEV::MilitaryPassportDocumentType_pskel&);

    void
    SovietPassport_parser (::SMEV::SovietPassportType_pskel&);

    void
    BirthCertificate_parser (::SMEV::SovietPassportType_pskel&);

    void
    DrivingLicenseRF_parser (::SMEV::DrivingLicenseRFType_pskel&);

    void
    ReleaseCertificate_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    PassportLossCertificate_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    Form9Certificate_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    TemporaryIdentityCardRF_parser (::SMEV::NotRestrictedDocumentType_pskel&);

    void
    parsers (::SMEV::PassportRFType_pskel& /* PassportRF */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* ForeignPassport */,
             ::SMEV::InternationalPassportRFType_pskel& /* ResidencePermitRF */,
             ::SMEV::InternationalPassportRFType_pskel& /* InternationalPassportRF */,
             ::SMEV::MilitaryPassportDocumentType_pskel& /* MilitaryPassport */,
             ::SMEV::MilitaryPassportDocumentType_pskel& /* SailorPassport */,
             ::SMEV::SovietPassportType_pskel& /* SovietPassport */,
             ::SMEV::SovietPassportType_pskel& /* BirthCertificate */,
             ::SMEV::DrivingLicenseRFType_pskel& /* DrivingLicenseRF */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* ReleaseCertificate */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* PassportLossCertificate */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* Form9Certificate */,
             ::SMEV::NotRestrictedDocumentType_pskel& /* TemporaryIdentityCardRF */);

    // Constructor.
    //
    AnyIdentityDocumentType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::PassportRFType_pskel* PassportRF_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* ForeignPassport_parser_;
    ::SMEV::InternationalPassportRFType_pskel* ResidencePermitRF_parser_;
    ::SMEV::InternationalPassportRFType_pskel* InternationalPassportRF_parser_;
    ::SMEV::MilitaryPassportDocumentType_pskel* MilitaryPassport_parser_;
    ::SMEV::MilitaryPassportDocumentType_pskel* SailorPassport_parser_;
    ::SMEV::SovietPassportType_pskel* SovietPassport_parser_;
    ::SMEV::SovietPassportType_pskel* BirthCertificate_parser_;
    ::SMEV::DrivingLicenseRFType_pskel* DrivingLicenseRF_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* ReleaseCertificate_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* PassportLossCertificate_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* Form9Certificate_parser_;
    ::SMEV::NotRestrictedDocumentType_pskel* TemporaryIdentityCardRF_parser_;
  };

  class NotRestrictedDocumentType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_NotRestrictedDocumentType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::string_20_pskel&);

    void
    Number_parser (::SMEV::Number_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::string_20_pskel& /* Series */,
             ::SMEV::Number_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    NotRestrictedDocumentType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::string_20_pskel* Series_parser_;
    ::SMEV::Number_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class PassportRFType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_PassportRFType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::digits_4_pskel&);

    void
    Number_parser (::SMEV::digits_6_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::digits_4_pskel& /* Series */,
             ::SMEV::digits_6_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    PassportRFType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::digits_4_pskel* Series_parser_;
    ::SMEV::digits_6_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class SovietPassportType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_SovietPassportType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::SovietStyleDocumentSeriesType_pskel&);

    void
    Number_parser (::SMEV::digits_6_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::SovietStyleDocumentSeriesType_pskel& /* Series */,
             ::SMEV::digits_6_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    SovietPassportType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::SovietStyleDocumentSeriesType_pskel* Series_parser_;
    ::SMEV::digits_6_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class InternationalPassportRFType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_InternationalPassportRFType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::digits_2_pskel&);

    void
    Number_parser (::SMEV::digits_7_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::digits_2_pskel& /* Series */,
             ::SMEV::digits_7_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    InternationalPassportRFType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::digits_2_pskel* Series_parser_;
    ::SMEV::digits_7_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class MilitaryPassportDocumentType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_MilitaryPassportDocumentType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::Series_pskel&);

    void
    Number_parser (::SMEV::digits_7_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::Series_pskel& /* Series */,
             ::SMEV::digits_7_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    MilitaryPassportDocumentType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::Series_pskel* Series_parser_;
    ::SMEV::digits_7_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class DrivingLicenseRFType_pskel: public ::xml_schema::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    Series ();

    virtual void
    Number ();

    virtual void
    IssueDate (const ::xml_schema::date&);

    virtual void
    Issuer ();

    virtual void
    post_DrivingLicenseRFType ();

    // Parser construction API.
    //
    void
    Series_parser (::SMEV::Series1_pskel&);

    void
    Number_parser (::SMEV::digits_6_pskel&);

    void
    IssueDate_parser (::xml_schema::date_pskel&);

    void
    Issuer_parser (::SMEV::rus_and_num_200_pskel&);

    void
    parsers (::SMEV::Series1_pskel& /* Series */,
             ::SMEV::digits_6_pskel& /* Number */,
             ::xml_schema::date_pskel& /* IssueDate */,
             ::SMEV::rus_and_num_200_pskel& /* Issuer */);

    // Constructor.
    //
    DrivingLicenseRFType_pskel ();

    // Implementation.
    //
    protected:
    virtual bool
    _start_element_impl (const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string&,
                         const ::xml_schema::ro_string*);

    virtual bool
    _end_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&);

    protected:
    ::SMEV::Series1_pskel* Series_parser_;
    ::SMEV::digits_6_pskel* Number_parser_;
    ::xml_schema::date_pskel* IssueDate_parser_;
    ::SMEV::rus_and_num_200_pskel* Issuer_parser_;
  };

  class RFC2046MimeTypesType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_RFC2046MimeTypesType ();
  };

  class PostalCodeRFType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_PostalCodeRFType ();
  };

  class PhoneNumberRFType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_PhoneNumberRFType ();
  };

  class EmailAddressType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_EmailAddressType ();
  };

  class LegalPersonINNType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_LegalPersonINNType ();
  };

  class PhysicalPersonINNType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_PhysicalPersonINNType ();
  };

  class SNILSType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_SNILSType ();
  };

  class KPPType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_KPPType ();
  };

  class OGRNCompanyType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_OGRNCompanyType ();
  };

  class OGRNSoleProprietorType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_OGRNSoleProprietorType ();
  };

  class CadastralNumberType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_CadastralNumberType ();
  };

  class OKATOType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_OKATOType ();
  };

  class GenderType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_GenderType ();
  };

  class SovietStyleDocumentSeriesType_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_SovietStyleDocumentSeriesType ();
  };

  class digits_7_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_digits_7 ();
  };

  class digits_6_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_digits_6 ();
  };

  class digits_4_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_digits_4 ();
  };

  class digits_2_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_digits_2 ();
  };

  class rus_and_num_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_and_num ();
  };

  class rus_and_num_500_pskel: public virtual ::SMEV::rus_and_num_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_and_num_500 ();
  };

  class rus_and_num_200_pskel: public virtual ::SMEV::rus_and_num_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_and_num_200 ();
  };

  class rus_and_num_100_pskel: public virtual ::SMEV::rus_and_num_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_and_num_100 ();
  };

  class rus_and_num_50_pskel: public virtual ::SMEV::rus_and_num_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_and_num_50 ();
  };

  class rus_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus ();
  };

  class rus_500_pskel: public virtual ::SMEV::rus_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_500 ();
  };

  class rus_200_pskel: public virtual ::SMEV::rus_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_200 ();
  };

  class rus_100_pskel: public virtual ::SMEV::rus_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_100 ();
  };

  class rus_50_pskel: public virtual ::SMEV::rus_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_rus_50 ();
  };

  class string_500_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_500 ();
  };

  class string_200_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_200 ();
  };

  class string_100_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_100 ();
  };

  class string_50_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_50 ();
  };

  class string_20_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_20 ();
  };

  class string_10_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_string_10 ();
  };

  class Number_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_Number ();
  };

  class Series_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_Series ();
  };

  class Series1_pskel: public virtual ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual void
    post_Series1 ();
  };
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX__SCHEMES_SCHEMA_COMMON_SMEV_SMEV_SUPPLEMENTARY_COMMONS_1_0_1_PSKEL_HXX
