#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace fteo {
    namespace schemes {
    using namespace System::Xml::Serialization;
    using namespace System;
    ref class TMyPolygon;
    ref class TMyPolygonTmyPointO;
    ref class TMyPolygonTMyOutLayer;
    ref class TMyPolygonTMyOutLayerTmyPointO;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"2.0.50727.1432"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
    System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
    public ref class TMyPolygon {
        
        private: cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  pointsField;
        
        private: System::Byte parent_IdField;
        
        private: System::String^  definitionField;
        
        private: System::Byte layer_idField;
        
        private: cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  childsField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlArrayItemAttribute(L"TmyPointO", IsNullable=false)]
        property cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  Points {
            cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  get();
            System::Void set(cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  value);
        }
        
        /// <remarks/>
        public: property System::Byte Parent_Id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::String^  Definition {
            System::String^  get();
            System::Void set(System::String^  value);
        }
        
        /// <remarks/>
        public: property System::Byte Layer_id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlArrayItemAttribute(L"TMyOutLayer", IsNullable=false)]
        property cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  Childs {
            cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  get();
            System::Void set(cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"2.0.50727.1432"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
    public ref class TMyPolygonTmyPointO {
        
        private: System::Byte fidField;
        
        private: System::Byte borderidField;
        
        private: System::Byte fStatusField;
        
        private: System::Byte numGeopointField;
        
        private: System::Byte orderField;
        
        private: System::UInt16 numGeopointAField;
        
        private: System::Decimal xField;
        
        private: System::Decimal yField;
        
        private: System::Byte zField;
        
        private: System::Decimal mtField;
        
        private: System::Byte idField;
        
        private: System::Byte statusField;
        
        /// <remarks/>
        public: property System::Byte fid {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Borderid {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte fStatus {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte NumGeopoint {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Order {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::UInt16 NumGeopointA {
            System::UInt16 get();
            System::Void set(System::UInt16 value);
        }
        
        /// <remarks/>
        public: property System::Decimal x {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Decimal y {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Byte z {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Decimal Mt {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Byte id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Status {
            System::Byte get();
            System::Void set(System::Byte value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"2.0.50727.1432"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
    public ref class TMyPolygonTMyOutLayer {
        
        private: cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  pointsField;
        
        private: System::Byte parent_IdField;
        
        private: System::Byte layer_idField;
        
        /// <remarks/>
        public: [System::Xml::Serialization::XmlArrayItemAttribute(L"TmyPointO", IsNullable=false)]
        property cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  Points {
            cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  get();
            System::Void set(cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  value);
        }
        
        /// <remarks/>
        public: property System::Byte Parent_Id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Layer_id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"2.0.50727.1432"), 
    System::SerializableAttribute, 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
    public ref class TMyPolygonTMyOutLayerTmyPointO {
        
        private: System::Byte fidField;
        
        private: System::Byte borderidField;
        
        private: System::Byte fStatusField;
        
        private: System::Byte numGeopointField;
        
        private: System::Byte orderField;
        
        private: System::UInt16 numGeopointAField;
        
        private: System::Decimal xField;
        
        private: System::Decimal yField;
        
        private: System::Byte zField;
        
        private: System::Decimal mtField;
        
        private: System::Byte idField;
        
        private: System::Byte statusField;
        
        /// <remarks/>
        public: property System::Byte fid {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Borderid {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte fStatus {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte NumGeopoint {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Order {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::UInt16 NumGeopointA {
            System::UInt16 get();
            System::Void set(System::UInt16 value);
        }
        
        /// <remarks/>
        public: property System::Decimal x {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Decimal y {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Byte z {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Decimal Mt {
            System::Decimal get();
            System::Void set(System::Decimal value);
        }
        
        /// <remarks/>
        public: property System::Byte id {
            System::Byte get();
            System::Void set(System::Byte value);
        }
        
        /// <remarks/>
        public: property System::Byte Status {
            System::Byte get();
            System::Void set(System::Byte value);
        }
    };
    }
}
namespace fteo {
    namespace schemes {
    
    
    inline cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  TMyPolygon::Points::get() {
        return this->pointsField;
    }
    inline System::Void TMyPolygon::Points::set(cli::array< fteo::schemes::TMyPolygonTmyPointO^  >^  value) {
        this->pointsField = value;
    }
    
    inline System::Byte TMyPolygon::Parent_Id::get() {
        return this->parent_IdField;
    }
    inline System::Void TMyPolygon::Parent_Id::set(System::Byte value) {
        this->parent_IdField = value;
    }
    
    inline System::String^  TMyPolygon::Definition::get() {
        return this->definitionField;
    }
    inline System::Void TMyPolygon::Definition::set(System::String^  value) {
        this->definitionField = value;
    }
    
    inline System::Byte TMyPolygon::Layer_id::get() {
        return this->layer_idField;
    }
    inline System::Void TMyPolygon::Layer_id::set(System::Byte value) {
        this->layer_idField = value;
    }
    
    inline cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  TMyPolygon::Childs::get() {
        return this->childsField;
    }
    inline System::Void TMyPolygon::Childs::set(cli::array< fteo::schemes::TMyPolygonTMyOutLayer^  >^  value) {
        this->childsField = value;
    }
    
    
    inline System::Byte TMyPolygonTmyPointO::fid::get() {
        return this->fidField;
    }
    inline System::Void TMyPolygonTmyPointO::fid::set(System::Byte value) {
        this->fidField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::Borderid::get() {
        return this->borderidField;
    }
    inline System::Void TMyPolygonTmyPointO::Borderid::set(System::Byte value) {
        this->borderidField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::fStatus::get() {
        return this->fStatusField;
    }
    inline System::Void TMyPolygonTmyPointO::fStatus::set(System::Byte value) {
        this->fStatusField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::NumGeopoint::get() {
        return this->numGeopointField;
    }
    inline System::Void TMyPolygonTmyPointO::NumGeopoint::set(System::Byte value) {
        this->numGeopointField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::Order::get() {
        return this->orderField;
    }
    inline System::Void TMyPolygonTmyPointO::Order::set(System::Byte value) {
        this->orderField = value;
    }
    
    inline System::UInt16 TMyPolygonTmyPointO::NumGeopointA::get() {
        return this->numGeopointAField;
    }
    inline System::Void TMyPolygonTmyPointO::NumGeopointA::set(System::UInt16 value) {
        this->numGeopointAField = value;
    }
    
    inline System::Decimal TMyPolygonTmyPointO::x::get() {
        return this->xField;
    }
    inline System::Void TMyPolygonTmyPointO::x::set(System::Decimal value) {
        this->xField = value;
    }
    
    inline System::Decimal TMyPolygonTmyPointO::y::get() {
        return this->yField;
    }
    inline System::Void TMyPolygonTmyPointO::y::set(System::Decimal value) {
        this->yField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::z::get() {
        return this->zField;
    }
    inline System::Void TMyPolygonTmyPointO::z::set(System::Byte value) {
        this->zField = value;
    }
    
    inline System::Decimal TMyPolygonTmyPointO::Mt::get() {
        return this->mtField;
    }
    inline System::Void TMyPolygonTmyPointO::Mt::set(System::Decimal value) {
        this->mtField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::id::get() {
        return this->idField;
    }
    inline System::Void TMyPolygonTmyPointO::id::set(System::Byte value) {
        this->idField = value;
    }
    
    inline System::Byte TMyPolygonTmyPointO::Status::get() {
        return this->statusField;
    }
    inline System::Void TMyPolygonTmyPointO::Status::set(System::Byte value) {
        this->statusField = value;
    }
    
    
    inline cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  TMyPolygonTMyOutLayer::Points::get() {
        return this->pointsField;
    }
    inline System::Void TMyPolygonTMyOutLayer::Points::set(cli::array< fteo::schemes::TMyPolygonTMyOutLayerTmyPointO^  >^  value) {
        this->pointsField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayer::Parent_Id::get() {
        return this->parent_IdField;
    }
    inline System::Void TMyPolygonTMyOutLayer::Parent_Id::set(System::Byte value) {
        this->parent_IdField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayer::Layer_id::get() {
        return this->layer_idField;
    }
    inline System::Void TMyPolygonTMyOutLayer::Layer_id::set(System::Byte value) {
        this->layer_idField = value;
    }
    
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::fid::get() {
        return this->fidField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::fid::set(System::Byte value) {
        this->fidField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::Borderid::get() {
        return this->borderidField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::Borderid::set(System::Byte value) {
        this->borderidField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::fStatus::get() {
        return this->fStatusField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::fStatus::set(System::Byte value) {
        this->fStatusField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::NumGeopoint::get() {
        return this->numGeopointField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::NumGeopoint::set(System::Byte value) {
        this->numGeopointField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::Order::get() {
        return this->orderField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::Order::set(System::Byte value) {
        this->orderField = value;
    }
    
    inline System::UInt16 TMyPolygonTMyOutLayerTmyPointO::NumGeopointA::get() {
        return this->numGeopointAField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::NumGeopointA::set(System::UInt16 value) {
        this->numGeopointAField = value;
    }
    
    inline System::Decimal TMyPolygonTMyOutLayerTmyPointO::x::get() {
        return this->xField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::x::set(System::Decimal value) {
        this->xField = value;
    }
    
    inline System::Decimal TMyPolygonTMyOutLayerTmyPointO::y::get() {
        return this->yField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::y::set(System::Decimal value) {
        this->yField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::z::get() {
        return this->zField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::z::set(System::Byte value) {
        this->zField = value;
    }
    
    inline System::Decimal TMyPolygonTMyOutLayerTmyPointO::Mt::get() {
        return this->mtField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::Mt::set(System::Decimal value) {
        this->mtField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::id::get() {
        return this->idField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::id::set(System::Byte value) {
        this->idField = value;
    }
    
    inline System::Byte TMyPolygonTMyOutLayerTmyPointO::Status::get() {
        return this->statusField;
    }
    inline System::Void TMyPolygonTMyOutLayerTmyPointO::Status::set(System::Byte value) {
        this->statusField = value;
    }
    }
}
