// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "P_CommonSimpleType_v02-pskel.hxx"

namespace Simple2
{
}

namespace Simple2
{
  // CadastralBlockType_pskel
  //

  void CadastralBlockType_pskel::
  post_CadastralBlockType ()
  {
  }

  // d21_1_pskel
  //

  void d21_1_pskel::
  post_d21_1 ()
  {
  }

  // d23_1_pskel
  //

  void d23_1_pskel::
  post_d23_1 ()
  {
  }

  // dValueHa_pskel
  //

  void dValueHa_pskel::
  post_dValueHa ()
  {
  }

  // i20_pskel
  //

  void i20_pskel::
  post_i20 ()
  {
  }

  // i6Min1_pskel
  //

  void i6Min1_pskel::
  post_i6Min1 ()
  {
  }

  // nn1_pskel
  //

  void nn1_pskel::
  post_nn1 ()
  {
  }

  // nn2_pskel
  //

  void nn2_pskel::
  post_nn2 ()
  {
  }

  // nn20_pskel
  //

  void nn20_pskel::
  post_nn20 ()
  {
  }

  // OKTMOType_pskel
  //

  void OKTMOType_pskel::
  post_OKTMOType ()
  {
  }

  // p20_pskel
  //

  void p20_pskel::
  post_p20 ()
  {
  }

  // p22Min1_pskel
  //

  void p22Min1_pskel::
  post_p22Min1 ()
  {
  }

  // s120_pskel
  //

  void s120_pskel::
  post_s120 ()
  {
  }

  // s150_pskel
  //

  void s150_pskel::
  post_s150 ()
  {
  }

  // s5000_pskel
  //

  void s5000_pskel::
  post_s5000 ()
  {
  }

  // sCertificate50_pskel
  //

  void sCertificate50_pskel::
  post_sCertificate50 ()
  {
  }

  // sInBounds_pskel
  //

  void sInBounds_pskel::
  post_sInBounds ()
  {
  }

  // sName500_pskel
  //

  void sName500_pskel::
  post_sName500 ()
  {
  }

  // sRegNumberCulture_pskel
  //

  void sRegNumberCulture_pskel::
  post_sRegNumberCulture ()
  {
  }

  // sRegNumberCardCulture_pskel
  //

  void sRegNumberCardCulture_pskel::
  post_sRegNumberCardCulture ()
  {
  }

  // sName500JPG_pskel
  //

  void sName500JPG_pskel::
  post_sName500JPG ()
  {
  }

  // sName500PDF_pskel
  //

  void sName500PDF_pskel::
  post_sName500PDF ()
  {
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

