// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "P_CommonSimpleType_v01-pskel.hxx"

namespace Simple1
{
}

namespace Simple1
{
  // s2_pskel
  //

  void s2_pskel::
  post_s2 ()
  {
  }

  // s3_pskel
  //

  void s3_pskel::
  post_s3 ()
  {
  }

  // s4_pskel
  //

  void s4_pskel::
  post_s4 ()
  {
  }

  // s6_pskel
  //

  void s6_pskel::
  post_s6 ()
  {
  }

  // s8_pskel
  //

  void s8_pskel::
  post_s8 ()
  {
  }

  // s9_pskel
  //

  void s9_pskel::
  post_s9 ()
  {
  }

  // s10_pskel
  //

  void s10_pskel::
  post_s10 ()
  {
  }

  // s11_pskel
  //

  void s11_pskel::
  post_s11 ()
  {
  }

  // s12_pskel
  //

  void s12_pskel::
  post_s12 ()
  {
  }

  // s13_pskel
  //

  void s13_pskel::
  post_s13 ()
  {
  }

  // s20_pskel
  //

  void s20_pskel::
  post_s20 ()
  {
  }

  // s25_pskel
  //

  void s25_pskel::
  post_s25 ()
  {
  }

  // s30_pskel
  //

  void s30_pskel::
  post_s30 ()
  {
  }

  // s40_pskel
  //

  void s40_pskel::
  post_s40 ()
  {
  }

  // s45_pskel
  //

  void s45_pskel::
  post_s45 ()
  {
  }

  // s50_pskel
  //

  void s50_pskel::
  post_s50 ()
  {
  }

  // s60_pskel
  //

  void s60_pskel::
  post_s60 ()
  {
  }

  // s100_pskel
  //

  void s100_pskel::
  post_s100 ()
  {
  }

  // s200_pskel
  //

  void s200_pskel::
  post_s200 ()
  {
  }

  // s250_pskel
  //

  void s250_pskel::
  post_s250 ()
  {
  }

  // s1_255_pskel
  //

  void s1_255_pskel::
  post_s1_255 ()
  {
  }

  // s255_pskel
  //

  void s255_pskel::
  post_s255 ()
  {
  }

  // s500_pskel
  //

  void s500_pskel::
  post_s500 ()
  {
  }

  // s512_pskel
  //

  void s512_pskel::
  post_s512 ()
  {
  }

  // s1000_pskel
  //

  void s1000_pskel::
  post_s1000 ()
  {
  }

  // s1500_pskel
  //

  void s1500_pskel::
  post_s1500 ()
  {
  }

  // s2000_pskel
  //

  void s2000_pskel::
  post_s2000 ()
  {
  }

  // s2046_pskel
  //

  void s2046_pskel::
  post_s2046 ()
  {
  }

  // s2500_pskel
  //

  void s2500_pskel::
  post_s2500 ()
  {
  }

  // s4000_pskel
  //

  void s4000_pskel::
  post_s4000 ()
  {
  }

  // l1_pskel
  //

  void l1_pskel::
  post_l1 ()
  {
  }

  // l3_pskel
  //

  void l3_pskel::
  post_l3 ()
  {
  }

  // l6_pskel
  //

  void l6_pskel::
  post_l6 ()
  {
  }

  // l11_pskel
  //

  void l11_pskel::
  post_l11 ()
  {
  }

  // sBIC_pskel
  //

  void sBIC_pskel::
  post_sBIC ()
  {
  }

  // sFamilyStatus_pskel
  //

  void sFamilyStatus_pskel::
  post_sFamilyStatus ()
  {
  }

  // sGUID_pskel
  //

  void sGUID_pskel::
  post_sGUID ()
  {
  }

  // sType_Unit_pskel
  //

  void sType_Unit_pskel::
  post_sType_Unit ()
  {
  }

  // sCertificate_pskel
  //

  void sCertificate_pskel::
  post_sCertificate ()
  {
  }

  // sName_pskel
  //

  void sName_pskel::
  post_sName ()
  {
  }

  // sName_Contour_pskel
  //

  void sName_Contour_pskel::
  post_sName_Contour ()
  {
  }

  // sCadastralBlock_R_pskel
  //

  void sCadastralBlock_R_pskel::
  post_sCadastralBlock_R ()
  {
  }

  // sCadastralNumber_R_pskel
  //

  void sCadastralNumber_R_pskel::
  post_sCadastralNumber_R ()
  {
  }

  // sCadastralBlock_R2_pskel
  //

  void sCadastralBlock_R2_pskel::
  post_sCadastralBlock_R2 ()
  {
  }

  // sID255_pskel
  //

  void sID255_pskel::
  post_sID255 ()
  {
  }

  // sIDREF255_pskel
  //

  void sIDREF255_pskel::
  post_sIDREF255 ()
  {
  }

  // d4_pskel
  //

  void d4_pskel::
  post_d4 ()
  {
  }

  // d10_2_pskel
  //

  void d10_2_pskel::
  post_d10_2 ()
  {
  }

  // d20_pskel
  //

  void d20_pskel::
  post_d20 ()
  {
  }

  // d20_1_pskel
  //

  void d20_1_pskel::
  post_d20_1 ()
  {
  }

  // d20_2_pskel
  //

  void d20_2_pskel::
  post_d20_2 ()
  {
  }

  // d22_1_pskel
  //

  void d22_1_pskel::
  post_d22_1 ()
  {
  }

  // d38_pskel
  //

  void d38_pskel::
  post_d38 ()
  {
  }

  // d38_2_pskel
  //

  void d38_2_pskel::
  post_d38_2 ()
  {
  }

  // i2_pskel
  //

  void i2_pskel::
  post_i2 ()
  {
  }

  // i3_pskel
  //

  void i3_pskel::
  post_i3 ()
  {
  }

  // i4_pskel
  //

  void i4_pskel::
  post_i4 ()
  {
  }

  // i22_pskel
  //

  void i22_pskel::
  post_i22 ()
  {
  }

  // i22Min1_pskel
  //

  void i22Min1_pskel::
  post_i22Min1 ()
  {
  }

  // i40_pskel
  //

  void i40_pskel::
  post_i40 ()
  {
  }

  // i_Min1Max99_pskel
  //

  void i_Min1Max99_pskel::
  post_i_Min1Max99 ()
  {
  }

  // p10_pskel
  //

  void p10_pskel::
  post_p10 ()
  {
  }

  // p22_pskel
  //

  void p22_pskel::
  post_p22 ()
  {
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

